version: '3.7'

services:
  db:
    image: database
    build: 
      context: ./app
      target: development
      dockerfile: ./Dockerfile
    restart: always
    environment:
      POSTGRES_DB: 'forum_db'
      POSTGRES_PASSWORD: 'admin'
    container_name: forum_database
    ports: 
      - 5432:5432