"""create-table

Revision ID: 2405d6f193c5
Revises: 
Create Date: 2022-03-29 22:31:50.843841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2405d6f193c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
